project:
  type: website
  output-dir: docs  # Change from _site to docs
  execute-dir: project  # This makes all code execute from project root


website:
  title: "ACT School Walking Analysis"
  description: "Geographic analysis of ACT school accessibility for walking students"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: population_analysis.qmd
        text: Population Analysis
      - href: walk_time.qmd
        text: Average Walk Time
      - href: optimal_school.qmd
        text: Optimal New School
      - href: method.qmd
        text: Methods & Assumptions
    right:
    - icon: github
      aria-label: GitHub
      href: https://github.com/Gippers
    - icon: globe
      aria-label: Personal Website
      href: https://www.thomasmartin.id.au

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toggle: true
    css: styles.css
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false