name: Deploy Pre-built Site
# Note, this will only update after local rendering of quarto
on:
  push:
    branches: [main]
    paths: ['quarto_docs/docs/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create .nojekyll file
        run: touch quarto_docs/docs/.nojekyll
        
      - name: Setup Pages
        uses: actions/configure-pages@v4  # Updated version
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4  # Updated from v2 to v3
        with:
          path: quarto_docs/docs
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Updated version